spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/movieapp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  poster: ${user.home}/movieApp/poster/

base:
  url: "http://localhost:8080"

